
// export const allItems = [
//     {
//         "name": "Italian",
//         "id": "m1",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/italian.png',
//         "class": "Meat",
//         "price": 8.35,
//     },
//     {
//         "name": "Venecia",
//         "id": "m2",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/venecia.png',
//         "class": "Meat",
//         "price": 8.65,
//     },
//     {
//         "name": "Meat",
//         "id": "m3",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/meat.png',
//         "class": "Meat",
//         "price": 9.25,
//     },
//     {
//         "name": "Cheese",
//         "id": "m4",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/cheese.png',
//         "class": "Meat",
//         "price": 7.95,
//     },
//     {
//         "name": "Argentina",
//         "id": "m5",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/venecia.png',
//         "class": "Vegetarian",
//         "price": 7.35,
//     },
//     {
//         "name": "Mushrooms",
//         "id": "m6",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/meat.png',
//         "class": "Vegetarian",
//         "price": 8.65,
//     },
//     {
//         "name": "Tomato",
//         "id": "m7",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/cheese.png',
//         "class": "Vegetarian",
//         "price": 8.35,
//     },
//     {
//         "name": "Italian x2",
//         "id": "m8",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/italian.png',
//         "class": "Vegetarian",
//         "price": 8.45,
//     },
//     {
//         "name": "Tomato",
//         "id": "m9",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/cheese.png',
//         "class": "SeaProducts",
//         "price": 7.35,
//     },
//     {
//         "name": "Palermo",
//         "id": "m10",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/meat.png',
//         "class": "SeaProducts",
//         "price": 8.65,
//     },
//     {
//         "name": "Argentina",
//         "id": "m11",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/venecia.png',
//         "class": "SeaProducts",
//         "price": 8.35,
//     },
//     {
//         "name": "Italian New",
//         "id": "m12",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/italian.png',
//         "class": "SeaProducts",
//         "price": 9.35,
//     },
//     {
//         "name": "Capri",
//         "id": "m13",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/meat.png',
//         "class":"Mushroom",
//         "price": 8.45,
//     },
//     {
//         "name": "Spicy",
//         "id": "m14",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/cheese.png',
//         "class":"Mushroom",
//         "price": 8.15
//     },
//     {
//         "name": "Italian x3",
//         "id": "m15",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/italian.png',
//         "class":"Mushroom",
//         "price": 8.95,
//     },
//     {
//         "name": "Roma",
//         "id": "m16",
//         "filling": "Filling: onion, potato, tomato, mushrooms, cheese, olives, meat...",
//         "src": '/items/venecia.png',
//         "class":"Mushroom",
//         "price": 7.95,
//     }
// ]